### ISSUE TITLE
Problem parsing PHPUnit

### ISSUE THREAD

**Issue by dericofilho** [dericofilho/php.oracle#3]
https://github.com/dericofilho/php.tools/issues/19

**Comment by Shaked** [comment]
Hey can you elaborate what needs to be done (meaning, what you have already figured out) so I might be able to help?

Thanks man.

**Comment by dericofilho** [comment]
I haven't figured out the exact spot where the loop is derailing yet. I have some backlog to finish in the other projects and I shall resume it ASAP.

**Comment by dericofilho** [comment]
The problem is that it is not capable yet of parsing Namespaces bounded by curly braces. Please manually update the sublime-phpfmt to https://github.com/dericofilho/sublime-phpfmt/commit/d4d60549d978e7482c1529edce6a73029c76267e
